"""create counseling records table

Revision ID: 9787374f9b05
Revises: 343d0ec21a89
Create Date: 2026-06-10 21:32:01.590688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9787374f9b05'
down_revision: Union[str, Sequence[str], None] = '343d0ec21a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counseling_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('counselor_id', sa.Uuid(), nullable=False),
    sa.Column('counseling_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counseling_records_counselor_id'), 'counseling_records', ['counselor_id'], unique=False)
    op.create_index(op.f('ix_counseling_records_id'), 'counseling_records', ['id'], unique=False)
    op.create_index(op.f('ix_counseling_records_student_id'), 'counseling_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counseling_records_student_id'), table_name='counseling_records')
    op.drop_index(op.f('ix_counseling_records_id'), table_name='counseling_records')
    op.drop_index(op.f('ix_counseling_records_counselor_id'), table_name='counseling_records')
    op.drop_table('counseling_records')
    # ### end Alembic commands ###
